#NodePort service - Open kube port for an application of service kind; in production NLB option will be advised, not exposing port directly
kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---
#Desired state of deployment. There can be many documents in one yml file. They need to be divided by ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2 #To pods
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER #Jenkins Kubernetes plugin allows to replace variables
        ports:
        - containerPort: 8080
